### ISSUE TITLE
Import error in Mainappilcation.java file

### ISSUE THREAD

**Issue by godwin12345** [MR03web/react-native-set-soft-input-mode#4]
error: package io.github.mr03web.softinputmodemodule does not exist

**Comment by MR03web** [comment]
use like this:
io.github.mr03web.softinputmode

**Comment by godwin12345** [comment]
Thanks

**Comment by wincod75** [comment]
Same problem, using the fix above throws new errors:
"error: cannot find symbol class softinputmode"
"error: cannot find symbol class SoftInputModePackage"

**EDIT**
Following "npm i react-native-set-soft-input-mode --save" pulled down old code. I had to manually updated code changes from commit a5954b59cadcadab9ba80bf35a3a7919ade1332e
